version: '3.8'

services:
  api:
    build: .
    container_name: tucows-knowledge-assistant
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
      - ./faiss_index:/app/faiss_index
    restart: unless-stopped
